version: '2'
services:
  load-test:
    build: 
      context: load-test
      args:
        ALPINE_VERSION: 3.10
    command: "-n google.com"
    environment:
      LOOKUP_SERVER: google.com
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5044
    depends_on: 
      - logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - 5044:5044
      - 9600:9600
    volumes: 
      - ./logstash:/usr/share/logstash/pipeline/
  #   depends_on: 
  #     - elastic
  # elastic:
  #   image: 