version: '3.7'
services:
  go-base:
    build: 
      context: load-test
      dockerfile: Dockerfile.base
      args:
        ALPINE_VERSION: 3.10
    image: go_base
  load-test:
    build: 
      context: load-test
    command: "-n google.com"
    environment:
      LOOKUP_SERVER: google.com
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5044
    depends_on: 
      - logstash
      - go-base
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - 5044:5044
      - 9600:9600
    volumes: 
      - ./logstash:/usr/share/logstash/pipeline/
    depends_on: 
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    ports: 
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000
